version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "8421:8080"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
